server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
         #-----------email---------------------
        - id: email-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/mail/**
        #-----------Keycloak---------------------
        - id: keycloakSanteVista
          uri: http://localhost:8082
          predicates:
            - Path=/api/keycloak/**
        #-----------SanteVista---------------------
        - id: SanteVista
          uri: http://localhost:8083
          predicates:
            - Path=/api/SanteVista/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  instance:
    hostname: gateway-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
