management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8888
spring:
    application:
        name: configServerSanteVista
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Hela22-gr/projetSanteVista/config-serverSanteVista.git
                    username: Hela22-gr
                    password: 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
                    clone-on-start: true
                    skipSslValidation: true
                    default-label: dev
